include: package:pedantic_mono/analysis_options.1.21.1.yaml

analyzer: 
  strong-mode: 
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    # - avoid_print
    # - use_key_in_widget_constructors
